


env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct

env = XCURSOR_THEME,theme_Extracted Theme
env = XCURSOR_SIZE,24

cursor {
    no_hardware_cursors = true
}


# exec-once = iwgtk


source = ~/.config/assets/palette/palette.conf

monitor =, highres@highrr, auto ,1.00

source = programs.conf
source = style.conf
source = input.conf
source = keys.conf
source = windows.conf
source = plugins.conf
source = wallpaper.conf
source = ~/.config/hypr/wallpaper.conf
