$backprimary	=	000000
$backsecondary	=	0a0a10
$backtertiary	=	14141e
$backquaternary	=	1e1e2c
$backquinary	=	28283a
$backsenary		=	323248
$backseptenary	=	3c3c56
$backoctonary	=	464664
$backnonary		=	505072
$backdecenary	=	5a5a80
$backundenary	=	64648e
$backduodenary	=	6e6e9c

$foreprimary	=	4a5280
$foresecondary	=	435075
$foretertiary	=	3d4870
$forequaternary	=	374065
$forequinary	=	313860
$foresenary		=	2b3055
$foreseptenary	=	25284a
$foreoctonary	=	1f2040
$forenonary		=	191835
$foredecenary	=	13102a
$foreundenary	=	0d0820
$foreduodenary	=	070515

$highprimary	=	c4c6d4
$highsecondary	=	b8bacb
$hightertiary	=	acadc2
$highquaternary	=	a0a2b9
$highquinary	=	9496b0
$highsenary		=	888aa7
$highseptenary	=	7c7e9e
$highoctonary	=	707295
$highnonary		=	64668c
$highdecenary	=	585a83
$highundenary	=	4c4e7a
$highduodenary	=	404271
